-- =============================================================================
-- CRM 系统用户管理与权限管理 数据库建库建表 DDL 脚本 (PostgreSQL 幂等安全版)
-- =============================================================================

-- 0. 创建通用自动更新时间戳的触发器函数
CREATE OR REPLACE FUNCTION update_timestamp_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- -----------------------------------------------------------------------------
-- 1. 用户主表 (sys_users)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sys_users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_no VARCHAR(64) NOT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  nickname VARCHAR(64) NOT NULL DEFAULT '',
  avatar_url VARCHAR(255) DEFAULT NULL,
  status SMALLINT NOT NULL DEFAULT 1,
  system_role VARCHAR(32) NOT NULL DEFAULT 'NONE',
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP DEFAULT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_no ON sys_users(user_no);
CREATE INDEX IF NOT EXISTS idx_status_role ON sys_users(status, system_role);

DROP TRIGGER IF EXISTS trg_sys_users_upd ON sys_users;
CREATE TRIGGER trg_sys_users_upd BEFORE UPDATE ON sys_users FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

-- -----------------------------------------------------------------------------
-- 2. 认证标识表 (user_auths)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_auths (
  auth_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  auth_type VARCHAR(20) NOT NULL,
  identifier VARCHAR(128) NOT NULL,
  credential VARCHAR(255) DEFAULT '',
  verified_at TIMESTAMP DEFAULT NULL,
  status SMALLINT NOT NULL DEFAULT 1,
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_auth_identifier ON user_auths(auth_type, identifier);
CREATE INDEX IF NOT EXISTS idx_user_id ON user_auths(user_id);

DROP TRIGGER IF EXISTS trg_user_auths_upd ON user_auths;
CREATE TRIGGER trg_user_auths_upd BEFORE UPDATE ON user_auths FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

-- -----------------------------------------------------------------------------
-- 3. 短信验证码表 (sms_verifications)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sms_verifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone VARCHAR(20) NOT NULL,
  code_hash VARCHAR(128) NOT NULL,
  scene VARCHAR(30) NOT NULL,
  expired_at TIMESTAMP NOT NULL,
  used_at TIMESTAMP DEFAULT NULL,
  attempts SMALLINT NOT NULL DEFAULT 0,
  ip_address VARCHAR(45) DEFAULT '',
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_phone_scene ON sms_verifications(phone, scene, created_at);

-- -----------------------------------------------------------------------------
-- 4. 企业表 (companies)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS companies (
  company_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_no VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  logo_url VARCHAR(255) DEFAULT NULL,
  owner_user_id BIGINT NOT NULL,
  status SMALLINT NOT NULL DEFAULT 1,
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_company_no ON companies(company_no);
CREATE INDEX IF NOT EXISTS idx_owner_user ON companies(owner_user_id);

DROP TRIGGER IF EXISTS trg_companies_upd ON companies;
CREATE TRIGGER trg_companies_upd BEFORE UPDATE ON companies FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

-- -----------------------------------------------------------------------------
-- 5. 企业成员关联表 (company_members)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS company_members (
  member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
  status SMALLINT NOT NULL DEFAULT 1,
  joined_at TIMESTAMP DEFAULT NULL,
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_company_user ON company_members(company_id, user_id);
CREATE INDEX IF NOT EXISTS idx_user_company ON company_members(user_id, company_id, status);

DROP TRIGGER IF EXISTS trg_company_members_upd ON company_members;
CREATE TRIGGER trg_company_members_upd BEFORE UPDATE ON company_members FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

-- -----------------------------------------------------------------------------
-- 6. 企业分组表 (groups)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS groups (
  group_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  parent_group_id BIGINT DEFAULT NULL,
  name VARCHAR(64) NOT NULL,
  description VARCHAR(255) DEFAULT '',
  status SMALLINT NOT NULL DEFAULT 1,
  created_by BIGINT NOT NULL,
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_company_parent ON groups(company_id, parent_group_id);

DROP TRIGGER IF EXISTS trg_groups_upd ON groups;
CREATE TRIGGER trg_groups_upd BEFORE UPDATE ON groups FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

-- -----------------------------------------------------------------------------
-- 7. 分组成员关联表 (group_members)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS group_members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  group_role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
  joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP DEFAULT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_group_user ON group_members(group_id, user_id);
CREATE INDEX IF NOT EXISTS idx_user_group ON group_members(user_id, group_id);

-- -----------------------------------------------------------------------------
-- 8. 分级管理授权表 (management_delegations)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS management_delegations (
  delegation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  group_id BIGINT NOT NULL,
  grantee_user_id BIGINT NOT NULL,
  granted_by BIGINT NOT NULL,
  scope VARCHAR(32) NOT NULL DEFAULT 'GROUP_MANAGE',
  status SMALLINT NOT NULL DEFAULT 1,
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_company_grantee ON management_delegations(company_id, grantee_user_id, status);
CREATE INDEX IF NOT EXISTS idx_group_id ON management_delegations(group_id);

DROP TRIGGER IF EXISTS trg_management_delegations_upd ON management_delegations;
CREATE TRIGGER trg_management_delegations_upd BEFORE UPDATE ON management_delegations FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

-- -----------------------------------------------------------------------------
-- 9. 统一资源实体表 (resources)
-- 说明：所有权由 resource_owners 维护，本表不再持有 owner_type/owner_id。
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resources (
  resource_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_no VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  resource_type VARCHAR(20) NOT NULL,
  parent_resource_id BIGINT DEFAULT NULL,
  creator_user_id BIGINT NOT NULL,
  file_size BIGINT DEFAULT 0,
  file_type VARCHAR(50) DEFAULT '',
  file_key VARCHAR(512) DEFAULT '',
  status SMALLINT NOT NULL DEFAULT 1,
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_resource_no ON resources(resource_no);
CREATE INDEX IF NOT EXISTS idx_parent_id ON resources(parent_resource_id);

DROP TRIGGER IF EXISTS trg_resources_upd ON resources;
CREATE TRIGGER trg_resources_upd BEFORE UPDATE ON resources FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

-- -----------------------------------------------------------------------------
-- 10. 资源所有者表 (resource_owners)
-- 说明：多所有者、支持转让，含有效期（valid_from 必填，valid_until 为空则一直有效）。
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resource_owners (
  ownership_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id BIGINT NOT NULL,
  owner_type VARCHAR(20) NOT NULL,
  owner_id BIGINT NOT NULL,
  valid_from TIMESTAMP NOT NULL,
  valid_until TIMESTAMP DEFAULT NULL,
  granted_by BIGINT NOT NULL,
  status SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_resource_owner ON resource_owners(resource_id, owner_type, owner_id);
CREATE INDEX IF NOT EXISTS idx_owner_lookup ON resource_owners(owner_type, owner_id, status);
CREATE INDEX IF NOT EXISTS idx_owner_validity ON resource_owners(resource_id, status, valid_from, valid_until);

DROP TRIGGER IF EXISTS trg_resource_owners_upd ON resource_owners;
CREATE TRIGGER trg_resource_owners_upd BEFORE UPDATE ON resource_owners FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

-- -----------------------------------------------------------------------------
-- 11. 资源显式授权表 (resource_permissions)
-- 说明：所有权关系由 resource_owners 维护；本表负责 READ/WRITE/OWNER 显式授权
--       （含有效期：valid_from 必填，valid_until 为空则一直有效）。
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resource_permissions (
  permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id BIGINT NOT NULL,
  grantee_type VARCHAR(20) NOT NULL,
  grantee_id BIGINT NOT NULL,
  permission_level VARCHAR(20) NOT NULL,
  valid_from TIMESTAMP NOT NULL,
  valid_until TIMESTAMP DEFAULT NULL,
  granted_by BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_resource_grantee ON resource_permissions(resource_id, grantee_type, grantee_id);
CREATE INDEX IF NOT EXISTS idx_grantee_lookup ON resource_permissions(grantee_type, grantee_id);
CREATE INDEX IF NOT EXISTS idx_grantee_validity ON resource_permissions(resource_id, permission_level, valid_from, valid_until);

DROP TRIGGER IF EXISTS trg_resource_permissions_upd ON resource_permissions;
CREATE TRIGGER trg_resource_permissions_upd BEFORE UPDATE ON resource_permissions FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

-- -----------------------------------------------------------------------------
-- 12. 数据行级权限规则表 (row_permission_rules)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS row_permission_rules (
  rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resource_id BIGINT NOT NULL,
  grantee_type VARCHAR(20) NOT NULL,
  grantee_id BIGINT NOT NULL,
  rule_type VARCHAR(32) NOT NULL,
  filter_expression JSONB DEFAULT NULL,
  status SMALLINT NOT NULL DEFAULT 1,
  created_by BIGINT NOT NULL,
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_resource_grantee ON row_permission_rules(resource_id, grantee_type, grantee_id);

DROP TRIGGER IF EXISTS trg_row_permission_rules_upd ON row_permission_rules;
CREATE TRIGGER trg_row_permission_rules_upd BEFORE UPDATE ON row_permission_rules FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

-- -----------------------------------------------------------------------------
-- 13. 审计查看权限表 (audit_permissions)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  audit_scope VARCHAR(32) NOT NULL,
  scope_details JSONB DEFAULT NULL,
  granted_by BIGINT NOT NULL,
  expired_at TIMESTAMP DEFAULT NULL,
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_user_audit UNIQUE (user_id)
);

DROP TRIGGER IF EXISTS trg_audit_permissions_upd ON audit_permissions;
CREATE TRIGGER trg_audit_permissions_upd BEFORE UPDATE ON audit_permissions FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

-- -----------------------------------------------------------------------------
-- 14. 系统审计日志表 (audit_logs)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS audit_logs (
  log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  user_type VARCHAR(32) NOT NULL,
  company_id BIGINT DEFAULT NULL,
  action VARCHAR(64) NOT NULL,
  resource_type VARCHAR(32) DEFAULT '',
  resource_id VARCHAR(64) DEFAULT '',
  detail JSONB DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT '',
  user_agent VARCHAR(255) DEFAULT '',
  status SMALLINT NOT NULL DEFAULT 1,
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_user_created ON audit_logs(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_company_created ON audit_logs(company_id, created_at);
CREATE INDEX IF NOT EXISTS idx_user_type_created ON audit_logs(user_type, created_at);
CREATE INDEX IF NOT EXISTS idx_action ON audit_logs(action);

-- -----------------------------------------------------------------------------
-- 15. 用户消息中心表 (user_messages)
-- 说明：站内消息中心；消息类型 SYSTEM / JOIN_REQUEST / INVITATION。
--       sms_notified 预留短信通知扩展点（当前不通过短信发送额外提醒）。
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_messages (
  message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  message_type VARCHAR(30) NOT NULL,
  title VARCHAR(128) NOT NULL,
  content VARCHAR(512) NOT NULL DEFAULT '',
  related_company_id BIGINT DEFAULT NULL,
  related_user_id BIGINT DEFAULT NULL,
  is_read SMALLINT NOT NULL DEFAULT 0,
  read_at TIMESTAMP DEFAULT NULL,
  sms_notified SMALLINT NOT NULL DEFAULT 0,
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_msg_user_created ON user_messages(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_msg_user_read ON user_messages(user_id, is_read);

-- -----------------------------------------------------------------------------
-- 16. 系统参数表 (system_settings)
-- 说明：K/V 结构存储系统级配置，如个人/企业存储配额上限，由系统管理员维护。
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key VARCHAR(64) NOT NULL,
  setting_value VARCHAR(255) NOT NULL DEFAULT '',
  description VARCHAR(255) DEFAULT '',
  updated_by BIGINT DEFAULT NULL,
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_setting_key ON system_settings(setting_key);

DROP TRIGGER IF EXISTS trg_system_settings_upd ON system_settings;
CREATE TRIGGER trg_system_settings_upd BEFORE UPDATE ON system_settings FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

-- 预置存储配额参数：storage.quota.personal=209715200(200MB), storage.quota.company=10737418240(10GB)
INSERT INTO system_settings (setting_key, setting_value, description) VALUES
  ('storage.quota.personal', '209715200', '个人存储上限（字节），默认 200MB'),
  ('storage.quota.company', '10737418240', '企业存储上限（字节），默认 10GB')
ON CONFLICT (setting_key) DO UPDATE SET setting_value = EXCLUDED.setting_value;

-- -----------------------------------------------------------------------------
-- 17. 个体存储配额表 (storage_quotas)
-- 说明：单个用户/个别企业的专属存储上限（字节），优先于全局默认配额，由系统管理员维护。
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS storage_quotas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quota_type VARCHAR(20) NOT NULL,
  subject_id BIGINT NOT NULL,
  quota_bytes BIGINT NOT NULL,
  updated_by BIGINT DEFAULT NULL,
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_quota_subject UNIQUE (quota_type, subject_id)
);

DROP TRIGGER IF EXISTS trg_storage_quotas_upd ON storage_quotas;
CREATE TRIGGER trg_storage_quotas_upd BEFORE UPDATE ON storage_quotas FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

-- -----------------------------------------------------------------------------
-- 18. 企业变更审批表 (company_approvals)
-- 说明：企业注销/所有权转让的审批流程记录（v3.5），由系统管理员或有权限的审计人员审批。
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS company_approvals (
  approval_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id BIGINT NOT NULL,
  approval_type VARCHAR(20) NOT NULL,
  requester_user_id BIGINT NOT NULL,
  target_user_id BIGINT DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  reviewed_by BIGINT DEFAULT NULL,
  review_note VARCHAR(255) DEFAULT NULL,
  reviewed_at TIMESTAMP DEFAULT NULL,
  valid_from TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  valid_until TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_approval_company ON company_approvals(company_id, status);
CREATE INDEX IF NOT EXISTS idx_approval_status ON company_approvals(status, created_at);

DROP TRIGGER IF EXISTS trg_company_approvals_upd ON company_approvals;
CREATE TRIGGER trg_company_approvals_upd BEFORE UPDATE ON company_approvals FOR EACH ROW EXECUTE FUNCTION update_timestamp_column();

-- =============================================================================
-- 预置初始化数据 (PostgreSQL 的 ON CONFLICT 语法)
-- =============================================================================
--INSERT INTO sys_users (user_id, user_no, nickname, status, system_role) 
--VALUES (1, 'USR_ADMIN_001', '系统超级管理员', 1, 'SYSTEM_ADMIN')
--ON CONFLICT (user_id) DO UPDATE SET user_id = EXCLUDED.user_id;
--
--INSERT INTO user_auths (user_id, auth_type, identifier, credential, status)
--VALUES (1, 'PHONE', '13800000000', '$2a$10$e8p2U41jZqF/.P8N1y70UeQ9.13dZ3W3R0ZkM3e5RkKz9X0E0Rk.m', 1)
--ON CONFLICT (auth_type, identifier) DO UPDATE SET user_id = EXCLUDED.user_id;